// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Miapp.Migrations
{
    [DbContext(typeof(MunicipalityContext))]
    [Migration("20211119185411_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Miapp.Models.Municipio", b =>
                {
                    b.Property<int>("municipioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("latitud")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("longitud")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("poblacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("municipioID");

                    b.ToTable("Municipio");
                });
#pragma warning restore 612, 618
        }
    }
}
