// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Miapp.Migrations
{
    [DbContext(typeof(ConsultoryContext))]
    [Migration("20211119185411_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Miapp.Models.Consultory", b =>
                {
                    b.Property<int>("IDPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Enfermedad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Medicina")
                        .IsRequired()
                        .HasColumnType("text");


                    b.HasKey("IDPaciente");

                    b.ToTable("Consultory");
                });
#pragma warning restore 612, 618
        }
    }
}
